### ISSUE TITLE
datagen python error

### ISSUE THREAD

**Issue by michaelclesi** [mlcommons/storage#60]
Wanting to run storage benchmark on a multi-node 4xA100 cluster; getting python errors on a single node using these commands (created container for benchmark):

```
cd /storage/

./benchmark.sh datasize --workload unet3d --accelerator-type a100 --num-accelerators 1 --num-client-hosts 1 --client-host-memory-in-gb 100

./benchmark.sh datagen --workload unet3d --accelerator-type a100 --num-parallel 1 --param dataset.num_files_train=1000 --param dataset.data_folder=/data/unet3d_data

./benchmark.sh run --hosts $(hostname) --workload unet3d --accelerator-type a100 --num-accelerators 1 --results-dir /data/resultsdir --param dataset.num_files_train=1000 --param dataset.data_folder=/data/unet3d_data
```

I get the error:

```
The benchmark will run for approx 27 minutes(best case)
Minimum 3662 files are required which will consume 499 GB of storage
----------------------------------------------
Set --param dataset.num_files_train=3662 with ./benchmark.sh datagen/run commands
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'results/unet3d/2024-04-08-10-53-55'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'results/unet3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: 'results'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[11981,1],0]
  Exit code:    1
--------------------------------------------------------------------------
mpirun: Error: unknown option "-o"
Type 'mpirun --help' for usage.
srun: error: mike179: task 0: Exited with exit code 1
Done
2024-04-08T10:53:58
```

**Comment by zhenghh04** [comment]
It says 

`OSError: [Errno 30] Read-only file system: 'results'
`
Looks like your /storage/ is read only.
